require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: enable
  SuggestExtensions: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
  Exclude:
    - 'spec/*/*spec.rb'

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true

Lint/Debugger:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive
